services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/summit_db
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - summit-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=summit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - summit-network

volumes:
  postgres_data:

networks:
  summit-network:
    driver: bridge 